env: "local"
interface: "wlo1"
enable_console_writer: true
http_server:
  address: "0.0.0.0:8080"
  timeout: 100s
  idle_timeout: 60s
filters:
  protocols:
    tcp: true
    udp: true
    icmp: true
    dns: true
  src_ip: ""
  dst_ip: ""
  ports: ""
processor_workers: 8
enable_metrics: true